markdown:    kramdown
fhp_id:      1
book_title:  "Shoot It Yourself"
book_slug:   "shoot-it-yourself"
book_author: "Ignacio Galvez"
asset_path:  "http://assets.farmhouse.co/publishing/1-shoot-it-yourself/images/"
